export const BOOKS_READ='BOOKS_READ';
export const ADD_TO_WISHLIST='ADD_TO_WISHLIST';
export const CHANGE_PAGE='CHANGE_PAGE';
export const RESET_BOOKS_READ='RESET_BOOKS_READ';
export const RESET_WISHLIST='RESET_WISHLIST';
